backend:
  name: github
  repo: missing-user/missing-user.github.io 
  branch: master
#publish_mode: editorial_workflow
media_folder: "images" # Media files will be stored in the repo under images/uploads
collections:
  - name: "posts"
    label: "Post"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    folder: "_posts"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Images", name: "images", widget: "image", media_library: {config: {multiple: true}}}
      - {label: "Live URL", name: "link", widget: "string", default: "https://jurasic.dev/projectlink/"}
      - {label: "Repository URL", name: "repository", widget: "string", default: "https://github.com/missing-user/projectlink/"}
      - {label: "Latex Support", name: "mathjax", widget: "boolean", default: false, required: false}
      - {label: "Body", name: "body", widget: "markdown", sanitize_preview: true}