backend:
  name: github
  repo: missing-user/missing-user.github.io 
  branch: master
  site_domain: admiring-carson-78d5f2.netlify.com
publish_mode: editorial_workflow
media_folder: "images" # Media files will be stored in the repo under images/uploads
collections:
  - name: "posts"
    label: "Post"
    folder: "_posts"
    filter:
      field: language
      value: en
    fields:
      - {label: "Language", name: "language"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "portfolio"
    label: "Portfolio"
    folder: "_portfolio"
    filter:
      field: language
      value: en
    fields:
      - {label: "Language", name: "language"}
      - {label: "Body", name: "body", widget: "markdown"}